### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by samsondav** [barelyknown/identical_sort_by#1]
Hey man, love the podcast.

By the way, this isn't a bug - Ruby's sort has never been stable. Look here: http://stackoverflow.com/questions/15442298/is-sort-in-ruby-stable

Two ways to get a stable sort:

``` ruby
class Enumberable
  def stable_sort
    n = 0
    sort_by {|x| n+= 1; [x, n]}
  end
end
```

OR (more readable, possibly less performant)

``` ruby
module Enumerable
  def stable_sort
    sort_by.with_index { |x, idx| [x, idx] }
  end
end
```

**Comment by barelyknown** [comment]
Thanks for the nice words...

Yeah, I saw that after I posted and made a little note at the top of that article. TIL!
